args: !!python/object:argparse.Namespace
  accelerator: auto
  audio_logmel_mean: -7.03
  audio_logmel_std: 4.66
  audio_mel_num_subsample: 128
  audio_mel_step_size: 16
  audio_mel_window_size: 32
  audio_num_mels: 80
  audio_raw_sample_rate: 44100
  audio_resampled_rate: 16000
  batch_size: 32
  covariance_coeff: 1.0
  data_path: ./data/kinetics400small/
  devices: 1
  exclude_bn_bias: false
  fp32: false
  invariance_coeff: 25.0
  learning_rate: 0.3
  max_epochs: 800
  nodes: 1
  online_ft: true
  optimizer: lars
  subsample_clip_duration: 1
  total_clip_duration: 8
  variance_coeff: 25.0
  video_crop_size: 224
  video_horizontal_flip_p: 0.5
  video_max_short_side_scale: 320
  video_means: !!python/tuple
  - 0.45
  - 0.45
  - 0.45
  video_min_short_side_scale: 256
  video_num_subsampled: 16
  video_path_prefix: ''
  video_stds: !!python/tuple
  - 0.225
  - 0.225
  - 0.225
  warmup_epochs: 10
  weight_decay: 0.0001
  workers: 0
